In [2]:
import numpy as np

# Square

Here is how to square elements of a NumPy array. The **numpy.square()** function returns a new array with each element being the square of the corresponding element in the input array.

In [4]:
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Calculate the square of each element
squared_arr = np.square(arr)

# Print the result
print(squared_arr)  # Output: [ 1  4  9 16 25]

[ 1  4  9 16 25]


# Square Root

**numpy.sqrt()** in Python is a function from the NumPy library used to compute the square root of each element in an array or a single number. It returns a new array of the same shape with the square roots of the input values. The function handles both positive and negative numbers, returning NaN for negative inputs when working with real numbers.

In [5]:
a = np.array([1, 4, 9, 16, 25])
b = np.sqrt(a)
print(b)

[1. 2. 3. 4. 5.]


# Pythagorean Theorem 
[Pythagorean Theorem Calculator](https://www.calculatorsoup.com/calculators/geometry-plane/pythagorean-theorem.php)

$a^2 + b^2 = c^2$

In [6]:
np.sqrt(np.square(2)+ np.square(3)) 

np.float64(3.605551275463989)

OR

In [7]:
a = np.array([2])
b = np.array([3])

result = np.hypot(a, b)

result

array([3.60555128])