In [1]:
import numpy as np

In [2]:
arr = np.arange(0,12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Single Dimensions Array

In [3]:
arr[2:6]

array([2, 3, 4, 5])

arr[2:6] means "get the elements from index 2 up to (but not including) index 6.

In [4]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

arr[2:] means "get all the elements from index 2 to the end of the array."

In [5]:
arr[:4]

array([0, 1, 2, 3])

arr[:4] means "get all the elements from the beginning up to (but not including) index 4.

# Multi Dimensions Arrays

The array numbers has three rows and four columns. Therefore, this array has a (3, 4) shape

In [3]:
arr = np.arange(0,12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
arr[1:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

1: means starting from the second row (index 1) to the end.

In [5]:
arr[1:,2:]

array([[ 6,  7],
       [10, 11]])

This is an array slicing operation. It is used to extract a subarray from arr.

- 1: means starting from the second row (index 1) to the end.
- 2: means starting from the third column (index 2) to the end.
  
Therefore, arr[1:, 2:] extracts the subarray consisting of the elements from the last two columns of the last two rows.

In [3]:
arr = np.arange(0,12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
arr[:3,:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

<a href="https://github.com/browntruck246/Data-Science/blob/main/Data-Science-Foundations-Python/context.md">Context</a>